// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6mCrd3dFqxi-OX9GDGjDgKYz9zhCpSAA',
    appId: '1:648241352380:web:962dd0aa5e04a478178ab9',
    messagingSenderId: '648241352380',
    projectId: 'test-f00a8',
    authDomain: 'test-f00a8.firebaseapp.com',
    storageBucket: 'test-f00a8.appspot.com',
    measurementId: 'G-1N6GKT02K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeg9xt6KH4aE5Ul2jPlnUFST2HGIWJo7w',
    appId: '1:648241352380:android:0fbfa0191f5002f4178ab9',
    messagingSenderId: '648241352380',
    projectId: 'test-f00a8',
    storageBucket: 'test-f00a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYoD7niSXsiBuVBBystqROsy0qQMnrKbI',
    appId: '1:648241352380:ios:079c2b92b0fb1fd9178ab9',
    messagingSenderId: '648241352380',
    projectId: 'test-f00a8',
    storageBucket: 'test-f00a8.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYoD7niSXsiBuVBBystqROsy0qQMnrKbI',
    appId: '1:648241352380:ios:8ca9d5bf4823da12178ab9',
    messagingSenderId: '648241352380',
    projectId: 'test-f00a8',
    storageBucket: 'test-f00a8.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
